### PR TITLE
Basic support for Conan search request

### PR DESCRIPTION
**Pull request by ChGen**
#5 Basic support for Conan search request (v1 protocol)

### CODE REVIEW

**Comment by ChGen** [comment]
@olenagerasimova , please review.

**Review by olenagerasimova — APPROVED** [review]
@ChGen thanks, looks good to me. But it's necessary to add unit tests for each slice in `ConansEntity` (I'd suggest to make separate test class for each slice) in the next PRs. You can check any adapter (debian, maven, python etc) to see how we write unite tests for slices.

**Review by g4s8 — APPROVED** [review]
@ChGen thanks

**Comment by g4s8** [comment]
@ChGen please link each PR to issue next time

**Pull request merged**
